-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.START_DATE = "1850.1.1"
NDefines.NGame.END_DATE = "5058.2.1"
NDefines.NGame.MAX_RANDOM_NEW_WORLD = "2.1.1"
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.0005
NDefines.NCountry.FREE_IDEA_GROUP_COST  = 10
NDefines.NCountry.PS_ADVANCE_TECH = 640
NDefines.NCountry.PS_BOOST_STABILITY = 120
NDefines.NCountry.PS_CHANGE_CULTURE = 20
NDefines.NCountry.REVOLT_TECH_MORALE = 0.0005
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_1_SIZE = 0
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_SIZE = 0
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 132
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.002
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 132
NDefines.NCountry.TECHS_TO_REFORM = 1000
NDefines.NCountry.PRIMITIVES_TECH_MODIFIER = 0.35
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_TECHNOLOGY = 100
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_RELIGION = 500